modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/IAFEnvoy/IceAndFire-CE/issues"
license = "LGPL-3.0"

[[mods]]
modId = "iceandfire"
version = "${version}"
displayName = "Ice And Fire Community Edition"
authors = "Alexthe666 (Origin Author), IAFEnvoy, xiaowu, uoay"
description = '''
An unofficial fork of Ice And Fire.
Dragons and other mythological creatures in minecraft.
'''
logoFile = "logo.png"

[[dependencies.iceandfire]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.197,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iceandfire]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iceandfire]]
modId = "uranus"
type = "required"
versionRange = "[2.3.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.iceandfire]]
modId = "jupiter"
type = "required"
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "iceandfire.mixins.json"
[[mixins]]
config = "iceandfire-neoforge.mixins.json"